server.port: 8080

bot:
  check:
    initialDelay: 60000
    fixedDelay: 60000

foreman:
  baseUrl: https://dashboard.foreman.mn
  apiUrl: https://api.foreman.mn

google:
  chatScope: https://www.googleapis.com/auth/chat.bot
  bucket: dev-william-foreman-g-chat-bot
  credentialOauthScope: https://www.googleapis.com/auth/cloud-platform
  #resourceStream: C:\Users\WilliamHoward\Desktop\service-acct.json

notifications:
  max: 10