#Development app.yaml file only must be specified to use during app engine deployment
#Just using the default service for app engine
runtime: java11
instance_class: F1

# Explicitly set the memory limit and maximum heap size for the Spring Boot app
env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=256m -XX:ActiveProcessorCount=2 -Xmx32m"